name: Bug Report
description: Report a bug or unexpected behavior in CONductOR
title: "[BUG]: "
labels: ["type:bug", "status:needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us investigate.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which CONductOR component is affected?
      options:
        - UI (ChatWindow)
        - Intent Routing
        - Browser Automation
        - PowerShell Execution
        - AI Service Handlers (ChatGPT/Claude/Perplexity)
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Start CONductOR
        2. Type command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Paste any error messages or relevant log output
      render: powershell

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severely does this impact your use of CONductOR?
      options:
        - Critical (Cannot use CONductOR)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor inconvenience)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: CONductOR Version
      description: Which version are you using? (Check Start-Assistant.ps1)
      placeholder: "v0.1.0"

  - type: input
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: Output of $PSVersionTable.PSVersion
      placeholder: "7.4.0"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Windows version
      placeholder: "Windows 11 23H2"

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included steps to reproduce
          required: true
        - label: I have included error messages/logs if applicable
          required: false
