name: Feature Request
description: Suggest a new feature or enhancement for CONductOR
title: "[FEATURE]: "
labels: ["type:feature", "status:needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your ideas for improving CONductOR.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which CONductOR component should this feature enhance?
      options:
        - UI (ChatWindow)
        - Intent Routing
        - Browser Automation
        - PowerShell Execution
        - AI Service Handlers (ChatGPT/Claude/Perplexity)
        - Configuration
        - New Component
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's missing from CONductOR?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should CONductOR address this problem?
      placeholder: "CONductOR could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: "Alternative approaches..."

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you'd use this feature
      placeholder: |
        # Example usage
        PS> Start-Assistant
        User: [Your example command]
        CONductOR: [Expected behavior]
      render: powershell

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Critical (Cannot use CONductOR without this)
        - High (Significantly improves workflow)
        - Medium (Nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Would you be willing to implement this feature?
      options:
        - Yes, I can submit a PR
        - Maybe, with guidance
        - No, but I can test it
        - No, just suggesting
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues/PRs to avoid duplicates
          required: true
        - label: This feature aligns with CONductOR's vision (Windows-native AI orchestration)
          required: true
        - label: I have considered backwards compatibility
          required: false
